name: array-tphasenet-test
channels:
  - conda-forge
dependencies:
  - python=3.10.12
  - pip=24.0
  - setuptools<81
  - jupyterlab=3.6.8
  - notebook=6.5.7
  - ipython=8.18.1
  - ipykernel=6.29.5
  - jupyter_server<2
  - jupyterlab_server<3
  - pytest
  - pip:
      - tensorflow==2.12.1
      - numpy==1.23.5
      - scipy==1.10.1
      - pandas==2.0.3
      - matplotlib==3.7.5
      - obspy==1.4.0
      - omegaconf==2.3.0
      - tqdm==4.66.2
      - h5py==3.8.0
      - osfclient
